apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: sample-python-app
  ports:
    - port: 80 #Exposing the service on port 80.
      targetPort: 8000 #The port where the application can be accessed.    
      nodePort: 30007 #The opening port of the cluster. clusterIP/30007 to access the cluster.
