apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels: #This is used to update existing pods with the below given label.
      app: nginx
  template:
    metadata: 
      labels: #This is used to create new pods with the specific label.
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      
