apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
# The Job runs a Perl script to calculate 2000 digits of Pi.
#If the Job fails, Kubernetes will retry it up to 4 times.
#If it keeps failing after 4 retries, Kubernetes gives up and marks the Job as "Failed".
