apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  labels:
    type: local
spec:
  storageClassName: standard #For cloud storage provisioning
  capacity:
    storage: 1Gi #1GB
  accessModes:
    - ReadWriteOnce #There are 4 access modes
  hostPath:
    path: "/home/ravindar/Devops/kube-practice/kubernetes-Practice/storageClass/localpv/"
    #Creating a local path inside our ubuntu machine
