---
apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
    environment: Testing
spec:
  containers:
    - name: appcontainer
      image: imranvisualpath/freshtomapp:V7
      ports:
        - name: vproapp-port
          containerPort: 8080 #Exposing port 8080

