apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  username: UG9kQWRtaW4=
  password: UG9kQWRtaW5TZWNyZXRQYXNzd29yZDg5MTM=
type: Opaque  #It specifies that the secret is generic(Password or username or api keys etc...) and the specifies that the message is encoded in base64.
