apiVersion: v1
kind: Pod
metadata:
  name: secret-read-pod
spec:
  containers:
  - name: mycontainer
    image: redis
    env: 
      - name: username
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: username
            optional: false
      - name: password
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password
            optional: false
  restartPolicy: Never
